# Generated by Django 4.2.6 on 2023-10-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('FILMES', 'Filmes'), ('SERIES', 'Séries'), ('DOCUMENTARIO', 'Documentario'), ('OUTROS', 'Outros')], max_length=15),
        ),
    ]
